"""add settlement id

Revision ID: 07bc294cf8b4
Revises: d753124135cf
Create Date: 2026-07-20 14:20:39.490557

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07bc294cf8b4'
down_revision: Union[str, Sequence[str], None] = 'd753124135cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('settlement_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'orders', 'settlements', ['settlement_id'], ['id'])
    op.drop_constraint(op.f('uq_shop_daily_settlement'), 'settlements', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_shop_daily_settlement'), 'settlements', ['shop_id', 'settlement_date'], postgresql_nulls_not_distinct=False)
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_column('orders', 'settlement_id')
    # ### end Alembic commands ###
