"""create shop queue

Revision ID: 291ee29dc564
Revises: 958596a1a94c
Create Date: 2026-07-12 13:26:37.918729

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '291ee29dc564'
down_revision: Union[str, Sequence[str], None] = '958596a1a94c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shop_queue',
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('queue_date', sa.Date(), nullable=False),
    sa.Column('queue_type', sa.Enum('PRIORITY', 'REGULAR', name='queuetype'), nullable=False),
    sa.Column('queue_number', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=20), nullable=False),
    sa.Column('queue_state', sa.Enum('WAITING', 'OPENED', 'PRINTING', 'READY', 'SERVED', 'REJECTED', name='queuestate'), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('downloaded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('printing_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ready_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('served_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_id'),
    sa.UniqueConstraint('queue_date', 'queue_type', 'queue_number', name='uq_daily_queue_number')
    )
    op.create_index('ix_shop_queue_current', 'shop_queue', ['is_current'], unique=False)
    op.create_index('ix_shop_queue_date', 'shop_queue', ['queue_date'], unique=False)
    op.create_index('ix_shop_queue_state', 'shop_queue', ['queue_state'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_shop_queue_state', table_name='shop_queue')
    op.drop_index('ix_shop_queue_date', table_name='shop_queue')
    op.drop_index('ix_shop_queue_current', table_name='shop_queue')
    op.drop_table('shop_queue')
    # ### end Alembic commands ###
