"""create waiting room

Revision ID: d753124135cf
Revises: 1f683efde802
Create Date: 2026-07-12 22:19:41.848629

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd753124135cf'
down_revision: Union[str, Sequence[str], None] = '1f683efde802'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('waiting_room',
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('entry_point', sa.Enum('NEW_ORDER', 'MY_ORDERS', 'PAYMENTS', name='waitingroomentry'), nullable=False),
    sa.Column('status', sa.Enum('WAITING', 'ADMITTED', 'LEFT', 'EXPIRED', name='waitingroomstatus'), nullable=False),
    sa.Column('session_token', sa.UUID(), nullable=True),
    sa.UniqueConstraint('session_token'),
    sa.Column('server_load_at_join', sa.Float(), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('admitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('left_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_waiting_room_joined_at'), 'waiting_room', ['joined_at'], unique=False)
    op.create_index(op.f('ix_waiting_room_status'), 'waiting_room', ['status'], unique=False)
    op.create_index(op.f('ix_waiting_room_student_id'), 'waiting_room', ['student_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_waiting_room_student_id'), table_name='waiting_room')
    op.drop_index(op.f('ix_waiting_room_status'), table_name='waiting_room')
    op.drop_index(op.f('ix_waiting_room_joined_at'), table_name='waiting_room')
    op.drop_table('waiting_room')
    # ### end Alembic commands ###
