"""add platform settings and pricing

Revision ID: e68337e68785
Revises: 820a768b6954
Create Date: 2026-07-07 21:14:33.118503

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'e68337e68785'
down_revision: Union[str, Sequence[str], None] = '820a768b6954'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('platform_settings',
    sa.Column('platform_fee', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('priority_fee', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('max_documents_per_order', sa.Integer(), nullable=False),
    sa.Column('max_upload_size_mb', sa.Integer(), nullable=False),
    sa.Column('max_pages_per_document', sa.Integer(), nullable=False),
    sa.Column('draft_expiry_hours', sa.Integer(), nullable=False),
    sa.Column('queue_timeout_minutes', sa.Integer(), nullable=False),
    sa.Column('allow_new_orders', sa.Boolean(), nullable=False),
    sa.Column('maintenance_mode', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pricing',
    sa.Column(
    "paper_size",
    postgresql.ENUM(
        name="papersize",
        create_type=False,
    ),
    nullable=False,
),

sa.Column(
    "print_type",
    postgresql.ENUM(
        name="printtype",
        create_type=False,
    ),
    nullable=False,
),

sa.Column(
    "print_side",
    postgresql.ENUM(
        name="printside",
        create_type=False,
    ),
    nullable=False,
),
    sa.Column('shop_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('convenience_fee', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pricing')
    op.drop_table('platform_settings')
    # ### end Alembic commands ###
